apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: mongo
  labels:
    app: mongo
spec:
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mongo
    spec:
      containers:
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: mongo
  labels:
    app: mongo
spec:
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mongo
    spec:
      containers:
      - image: mongo:latest
        name: mongo
        imagePullPolicy: Always
        ports:
        - containerPort: 27017
          name: mongo
---
apiVersion: v1
kind: Service
metadata:
  name: mongo
  labels:
    app: mongo
spec:
  ports:
    - port: 27017
      targetPort: 27017
  selector:
    app: mongo
  type: NodePort
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: application-with-sidecars
  labels:
    app: application-with-sidecars
spec:
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: application-with-sidecars
    spec:
      containers:
      - image: 127.0.0.1:30400/application:latest
        name: application
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
          name: application
      - image: 127.0.0.1:30400/rest:latest
        name: rest
        imagePullPolicy: Always
        ports:
        - containerPort: 3001
          name: rest
      - image: 127.0.0.1:30400/soap:latest
        name: soap
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
          name: soap
---
apiVersion: v1
kind: Service
metadata:
  name: application
  labels:
    app: application-with-sidecars
spec:
  ports:
    - port: 5000
      targetPort: 5000
  selector:
    app: application-with-sidecars
  type: NodePort
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
 name: application
spec:
  backend:
    serviceName: application
    servicePort: 5000
  rules:
  - host: application.192.168.99.100.xip.io
    http:
      paths:
      - path: /
        backend:
          serviceName: application
          servicePort: 5000
